import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import DashboardLayout from '@/components/layouts/DashboardLayout';
import PhysicalCountEditor, { invalidCountLines } from '@/components/inventory/PhysicalCountEditor';
import { useAuthGuard } from '@/hooks/useAuthGuard';
import { cancelPhysicalCount, fetchCountReferences, fetchPhysicalCount, postPhysicalCount, refreshPhysicalCount, updatePhysicalCount, type CountLineInput } from '@/lib/inventoryPhysicalCountsApi';
import type { CountReferences, PhysicalCount, PhysicalCountReason } from '@/types/inventoryPhysicalCount';

export default function PhysicalCountDetailPage() {
  useAuthGuard('inventory.read'); const router = useRouter(); const id = Number(router.query.id);
  const [count, setCount] = useState<PhysicalCount | null>(null); const [refs, setRefs] = useState<CountReferences>({ warehouses: [], products: [] });
  const [lines, setLines] = useState<CountLineInput[]>([]); const [reason, setReason] = useState<PhysicalCountReason>('PHYSICAL_COUNT'); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const readOnly = count?.status !== 'DRAFT';
  async function load() { if (!Number.isInteger(id) || id <= 0) return; const data = await fetchPhysicalCount(id); const references = await fetchCountReferences(data.warehouseId); setCount(data); setRefs({ ...references, products: references.products.map(product => { const item = data.items.find(candidate => candidate.productId === product.id); return { ...product, systemQuantity: item?.systemQuantitySnapshot ?? product.systemQuantity, unitCostEstimate: item?.unitCostSnapshot ?? product.unitCostEstimate }; }) }); setLines(data.items.map(item => ({ productId: item.productId, countedQuantity: item.countedQuantity }))); setReason(data.reason); setNotes(data.notes ?? ''); }
  useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : 'No fue posible cargar el conteo')); }, [id]);
  const impact = useMemo(() => count?.items.reduce((sum, item) => sum + Number(item.estimatedValueVariance ?? 0), 0) ?? 0, [count]);
  async function action(work: () => Promise<PhysicalCount>, validateLines = false) { if (validateLines && invalidCountLines(lines)) return setError('Corrige las cantidades físicas inválidas.'); setBusy(true); setError(''); try { const data = await work(); setCount(data); setLines(data.items.map(item => ({ productId: item.productId, countedQuantity: item.countedQuantity }))); setRefs(current => ({ ...current, products: current.products.map(product => { const item = data.items.find(candidate => candidate.productId === product.id); return item ? { ...product, systemQuantity: item.systemQuantitySnapshot, unitCostEstimate: item.unitCostSnapshot } : product; }) })); } catch (e) { const body = (e as Error & { body?: { code?: string } }).body; setError(body?.code === 'INVENTORY_PHYSICAL_COUNT_STALE' ? 'El inventario cambió. Actualiza los saldos y vuelve a contar los productos.' : e instanceof Error ? e.message : 'No fue posible completar la acción'); } finally { setBusy(false); } }
  if (!count) return <DashboardLayout><p>{error || 'Cargando conteo…'}</p></DashboardLayout>;
  return <DashboardLayout><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold text-[#001F3F]">Conteo físico #{count.id}</h1><p className="mt-1 text-gray-600">{count.status} · {count.warehouse.name}</p></div>{count.postedAt && <p>Publicado {new Date(count.postedAt).toLocaleString('es-CO')} por {count.postedBy?.fullName ?? count.postedBy?.email}</p>}{count.cancelledAt && <p>Cancelado {new Date(count.cancelledAt).toLocaleString('es-CO')} por {count.cancelledBy?.fullName ?? count.cancelledBy?.email}</p>}</div><div className="mt-5 rounded-2xl bg-white p-6 shadow"><PhysicalCountEditor references={refs} warehouseId={count.warehouseId} lines={lines} reason={reason} notes={notes} readOnly={readOnly} onLines={setLines} onReason={setReason} onNotes={setNotes} />{count.status === 'POSTED' && <div className="mt-5 rounded bg-blue-50 p-4"><p>Impacto estimado total: <strong>{impact.toLocaleString('es-CO', { style: 'currency', currency: 'COP' })}</strong></p><p className="text-sm">Valoración estimada; no constituye contabilidad formal.</p><ul className="mt-2 text-sm">{count.items.map(item => <li key={item.id}>{item.product.name}: movimiento {item.inventoryMovementId ? `#${item.inventoryMovementId}` : 'sin movimiento (diferencia cero)'}</li>)}</ul></div>}{error && <p role="alert" className="mt-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}{count.status === 'DRAFT' && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void action(() => updatePhysicalCount(count.id, { reason, notes: notes || null, items: lines }), true)} className="rounded border px-4 py-2">Guardar borrador</button><button disabled={busy} onClick={() => void action(async () => { await updatePhysicalCount(count.id, { reason, notes: notes || null, items: lines }); return postPhysicalCount(count.id); }, true)} className="rounded bg-[#001F3F] px-4 py-2 font-semibold text-white">Publicar ajuste</button><button disabled={busy} onClick={() => void action(() => refreshPhysicalCount(count.id))} className="rounded border border-amber-500 px-4 py-2 text-amber-800">Actualizar saldos y recontar</button><button disabled={busy} onClick={() => void action(() => cancelPhysicalCount(count.id))} className="rounded border border-red-500 px-4 py-2 text-red-700">Cancelar borrador</button></div>}</div></DashboardLayout>;
}
